### ISSUE TITLE
Upgrade to latest ADAL NuGet packages in both projects

### ISSUE THREAD

**Issue by mdocter** [JimDaly/CRMWebAPILoginControl#1]
I'm trying to get the 'CRMJSWebAPIServiceUtil' to work, but it depends on the 'Microsoft.IdentityModel.Clients.ActiveDirectory' v3.13.4.878 package which is missing in the project references/NuGet  installed packages list.

This login control uses v2.9.10826.1824 of this library, which is conflicting. 
BTW. I wonder how you got this version. It's probably some nightly build. My NuGet version list doesn't show it. The stable versions jump from 1.0.5 to 2.22.302111727.

Can you please upgrade the login control to use version 3.13.4.878 of the ADAL lib?

**Comment by JimDaly** [comment]
Maarten -
Recommend you remove both the 'Microsoft.IdentityModel.Clients.ActiveDirectory' and 'Microsoft.CrmSdk.WebApi.Samples.HelperCode' Nuget packages and then re-install **only** the 'Microsoft.CrmSdk.WebApi.Samples.HelperCode' Nuget package. This should bring in the v2.9.10826.1824 of the 'Microsoft.IdentityModel.Clients.ActiveDirectory' since it is a dependency.

Then, make sure you don't choose to upgrade to the latest version of 'Microsoft.IdentityModel.Clients.ActiveDirectory'.

v3 of the Microsoft.IdentityModel.Clients.ActiveDirectory library introduced a breaking change where the acquiretoken method no longer provides parameters for username and password. Not sure why they did this, but we haven't yet gotten to updating our code to adapt. We will eventually, and I expect it will change the way this control works.

Not sure how the AzureAD team _unlisted_ the v2.9 package. I have installed it from NuGet many times and have seen it in the list there in the past. It still seems to work, but it is not available as a choice.

Pretty sure the AzureAD folks are not considering that people might need to connect to a product that could be either using windows credentials _OR_ online, the way that CRM is available.

Let me know if the recommendation above doesn't work

BTW - I see that the AzureAD team posted that there are security issues with [multiple versions of their assemblies](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet#security-issue-in-multiple-versions-of-adal-net) which explains why this version was unlisted. This raises the urgency to make the sample code so it doesn't depend on one of those versions.

**Comment by mdocter** [comment]
Thanks Jim! Got it to work. The library / output looks great!

**Comment by JimDaly** [comment]
When the SDK Sample helpers are updated, I will update this login control to use them. Leaving this open until that is done.

**Comment by mdocter** [comment]
Hi Jim,

Imho the login control shouldn't be depended on the samples HelperCode. It should be as stand-alone / dependency-less as possible.

I got it to work by adding the ADAL v2.9 NuGet package to the `packages.config` file of the CRMJSWebAPIServiceUtil project and then ran a `Update-Package -Reinstall`. So my `packages.config` now looks like this:

``` xml
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="AjaxMin" version="5.14.5506.26202" targetFramework="net452" />
  <package id="Microsoft.IdentityModel.Clients.ActiveDirectory" version="2.9.10826.1824" targetFramework="net452" />
  <package id="Newtonsoft.Json" version="9.0.1" targetFramework="net452" />
</packages>
```

BTW. I think your tool would be a great plugin for the [XrmToolbox](http://www.xrmtoolbox.com).

**Comment by JimDaly** [comment]
Being stand-alone and dependency-less as possible is the goal. You will note that there are no CRM SDK assemblies used. The relatively small amount of helper code simply manages the use of the ADAL assemblies. I can go ahead and further modify the helper code so that it will use the newer ADAL assemblies.

**Comment by JimDaly** [comment]
It has been a couple of years since this was opened, but I've decided not to try and chase the latest ADAL assembly versions. (which are now up to 4.x)
The 2.x generation libraries are the only ones that allow managing password data which is captured in the UI of this control. 
The 3.x generation and higher will simply open the AD login dialog and manage it without the UI, which is the key part of this project.

There is no requirement to use the latest versions of these ADAL libraries and if this control is being used for managing user credentials and connection information, there is no point in upgrading.
